[GLOBAL]
pants_version = "2.21.0.dev4"
backend_packages.add = [
  "pants.backend.shell",
  "pants.backend.experimental.adhoc",
  "pants.backend.python",
]
build_patterns = ["BUILD.pants"]

[tailor]
build_file_name = "BUILD.pants"

[python]
# The default interpreter constraints for code in this repo.
interpreter_constraints = ["==3.10.*"]

[source]
root_patterns = ["/"]

[anonymous-telemetry]
enabled = false

[environments-preview.names]
workspace = "//cpp:workspace-cpp"
