[GLOBAL]
pants_version = "2.21.0.dev4"
backend_packages.add = [
  "pants.backend.shell",
  "pants.backend.experimental.adhoc",
]
pants_ignore = [
  "bazel-jvm/bazel-*/**"
]
build_ignore = [
  "bazel-jvm/BUILD*",
  "bazel-jvm/**/BUILD*",
]

[source]
root_patterns = ["/"]

[anonymous-telemetry]
enabled = false

[environments-preview.names]
workspace = "//:workspace"
